/**
 * Builds the storefront widget straight into the WordPress plugin's assets
 * directory, so the plugin ships a ready bundle and the store never needs a
 * build step on the server.
 */
import * as esbuild from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outfile = path.resolve(here, '../wordpress-plugin/wellness-chatbot/assets/js/widget.js');

const options = {
  entryPoints: [path.resolve(here, 'src/index.ts')],
  outfile,
  bundle: true,
  format: 'iife',
  target: ['es2019'],
  minify: !process.argv.includes('--watch'),
  sourcemap: false,
  legalComments: 'none',
  banner: {
    js: '/* Wellness World chat widget — built from widget/src. Do not edit this file directly. */',
  },
};

if (process.argv.includes('--watch')) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log(`Watching… output: ${outfile}`);
} else {
  const result = await esbuild.build({ ...options, metafile: true });
  const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
  console.log(`Built ${outfile} (${(bytes / 1024).toFixed(1)} kB)`);
}
