/**
 * Builds the storefront bundles straight into the WordPress plugin's assets
 * directory, so the plugin ships ready files and the store never needs a
 * build step on the server.
 *
 * Two independent bundles, not one: the chat widget loads on every page,
 * while the skin/hair analyzers load only on their own shortcode pages.
 * esbuild rejects `outfile` alongside multiple `entryPoints`, so each target
 * gets its own build — which also keeps each banner accurate.
 */
import * as esbuild from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const assets = path.resolve(here, '../wordpress-plugin/wellness-chatbot/assets/js');

const base = {
  bundle: true,
  format: 'iife',
  target: ['es2019'],
  minify: !process.argv.includes('--watch'),
  sourcemap: false,
  legalComments: 'none',
};

const targets = [
  {
    name: 'chat widget',
    entry: path.resolve(here, 'src/index.ts'),
    outfile: path.join(assets, 'widget.js'),
  },
  {
    name: 'skin/hair analyzer',
    entry: path.resolve(here, 'src/analyzer.ts'),
    outfile: path.join(assets, 'analyzer.js'),
  },
];

function optionsFor(target) {
  return {
    ...base,
    entryPoints: [target.entry],
    outfile: target.outfile,
    banner: {
      js: `/* Wellness World ${target.name} — built from widget/src. Do not edit this file directly. */`,
    },
  };
}

if (process.argv.includes('--watch')) {
  // One context per outfile: a single context cannot drive two of them.
  for (const target of targets) {
    const ctx = await esbuild.context(optionsFor(target));
    await ctx.watch();
    console.log(`Watching ${target.name} → ${target.outfile}`);
  }
} else {
  for (const target of targets) {
    const result = await esbuild.build({ ...optionsFor(target), metafile: true });
    // Each build emits exactly one output, but sum rather than index [0] so
    // this keeps telling the truth if that ever stops being the case.
    const bytes = Object.values(result.metafile.outputs).reduce((total, o) => total + o.bytes, 0);
    console.log(`Built ${target.outfile} (${(bytes / 1024).toFixed(1)} kB)`);
  }
}
